services:
  codeassistback:
    network_mode: host
    build: .
    #    ports:
    #      - '3002:3002'
    environment:
      - PORT=3030
      - suggestionkey=${suggestionkey}
      - copilotKey=${copilotKey}
      - copilotResource=${copilotResource}
      - geminisKey=${geminisKey}
      - openaiKey=${openaiKey}
  mongodb:
    image: mongo:latest
    container_name: mongodbcodea
    networks:
      - mongo-net
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=appUser
      - MONGO_INITDB_ROOT_PASSWORD=appPassword123
    volumes:
      - ./data/db:/data/db

networks:
  mongo-net:
    driver: bridge