/*
 * This source file was generated by the Gradle 'init' task
 */
package com.co.code.assistant;

import com.co.code.assistant.configurations.ApplicationModuleConfiguration;
import com.co.code.assistant.configurations.ApplicationStarter;

import static com.google.inject.Guice.createInjector;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.setProperty("java.locale.providers", "JRE");
        createInjector(new ApplicationModuleConfiguration()).getInstance(ApplicationStarter.class).run(args);
    }
}
